name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

env:
  CI: true

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 14.x
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test:ember
